apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: nginx-longhorn-pvc
