apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html
  restartPolicy: Never
  volumes:
  - name: vol
    hostPath:
      path: /data/nginx
